/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function start(args: Array<string>): Promise<number>
/** Launch in a blocking way */
export function startSync(args: Array<string>): number
