/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BsSystem {
  constructor()
  start(args: Array<string>, signal: AbortSignal): Promise<number>
  send(arg: any): void
  stop(): void
}
export type JsBsSystem = BsSystem

/** Launch in a blocking way */
export declare function startBlocking(args: Array<string>): number
