/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Launch in a blocking way */
export declare function startBlocking(args: Array<string>): number
export type JsBsSystem = BsSystem
export class BsSystem {
  constructor()
  start(args: Array<string>, signal: AbortSignal): Promise<unknown>
  send(arg: any): void
  stop(): void
}
