[package]
name = "bsnext_client"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
bsnext_dto = { path = "../bsnext_dto" }
