[package]
name = "bsnext_html"
version = "0.2.3"
edition = "2021"

[dependencies]
bsnext_input = { path = "../bsnext_input" }
unindent = "0.2.3"
indent = "0.1.1"
scraper = "0.21.0"

[dev-dependencies]
anyhow = { workspace = true }
insta = { workspace = true }
