name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  build-rust-binary:
    runs-on: macos-latest
    env:
      # Ensure the correct target architecture is set
      CARGO_TARGET_DIR: target
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4

      # Set up Rust with the appropriate toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Cache the Cargo registry and build directory to speed up builds
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      # Install dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm ci

      # Build the Rust binary with napi
      - name: Build Rust Binary with napi
        run: npm run build -- --target aarch64-apple-darwin

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
